name        : reiserfsprogs
version     : 3.6.24
release     : 2
source      :
    - https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v3.6.24/reiserfsprogs-3.6.24.tar.xz : 7e44fefe557d68a642191428210f3d64d80283b9ad0e45c24130f6ce936b0760
homepage    : https://reiser4.wiki.kernel.org/index.php/Main_Page
license     :
    - GPL-2.0
summary     : The tools to maintain a ReiserFS (Reiser v3) filesystem
component   : system.utils
description : |
    The tools to maintain a ReiserFS (Reiser v3) filesystem
setup      : |
    %configure CFLAGS="$CFLAGS -std=gnu89"
build      : |
    %make
install    : |
    %make_install
