name       : reiserfsprogs
version    : 3.6.27
release    : 4
source     :
    - https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v3.6.27/reiserfsprogs-3.6.27.tar.xz : 0e95b67fa7746a3c2d59145e9b9c2feb4a6be52853e83b497b182eae508e62e3
homepage   : https://reiser4.wiki.kernel.org/index.php/Main_Page
license    : GPL-2.0-only
summary    : The tools to maintain a ReiserFS (Reiser v3) filesystem
component  : system.utils
description: |
    The tools to maintain a ReiserFS (Reiser v3) filesystem
builddeps  :
    - pkgconfig(com_err)
    - acl-devel
setup      : |
    %patch -p1 < $pkgfiles/reiserfsprogs-3.6.27-loff_t.patch
    %reconfigure CFLAGS="$CFLAGS -std=gnu89"
build      : |
    %make
install    : |
    %make_install
